### ISSUE TITLE
为什么会这样呀

### ISSUE THREAD

**Issue by 666lbwnb** [laogui2008/heroku_hostloc_get_points2#2]
![image](https://user-images.githubusercontent.com/63054619/131241055-b4f28957-1b7c-43b6-98f8-15c64531652b.png)

**Comment by laogui2008** [comment]
使用说明中的 f 和 g 两个步骤都操作了吗？
![8](https://user-images.githubusercontent.com/6753846/131258297-aaa879e7-b893-4695-81b5-49fa19d0a557.png)

**Comment by 666lbwnb** [comment]
大佬我现在成功了，感谢
